WebApplication5/Models/ErrorViewModel.cs
namespace WebApplication5.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

WebApplication5/Models/Kitap.cs
using System.ComponentModel.DataAnnotations;

namespace WebApplication5.Models
{
	public class Kitap
	{
		[Key]
		public int KitapID { get; set; }
		[Required]
		[MaxLength(100)]
		[Display(Name = "Kitap Adı")]
		public string KitapAdi { get; set; }
		public int YazarID { get; set;}
		public Yazar Yazar { get; set;}
	}
}

WebApplication5/Models/KitaplikContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication5.Models
{
	public class KitaplikContext: DbContext
	{
		public DbSet<Kitap> Kitaplar { get; set; }
		public DbSet<Yazar> Yazarkar { get; set; }

		protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
		{
			optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;
            Database=KitaplikYazOkulu;Trusted_Connection=True;");
		}
	}
}

WebApplication5/Models/Yazar.cs
using System.ComponentModel.DataAnnotations;

namespace WebApplication5.Models
{
	public class Yazar
	{
		public int YazarID { get; set; }
		[Required]
		[MaxLength(100)]
		[Display(Name = "Yazar Ad")]
		public string YazarAd { get; set; }
		[Required]
		[MaxLength(100)]
		[Display(Name = "Yazar Soyad")]
		public string YazarSoyad { get; set; }
		public ICollection<Kitap> Kitaplar { get; set; }
	}
}

WebApplication5/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApplication5.Models;

namespace WebApplication5.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

WebApplication5/Controllers/YazarController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication5.Models;

namespace WebApplication5.Controllers
{
	public class YazarController : Controller
	{
		KitaplikContext k = new KitaplikContext();
		public IActionResult Index()
		{
			return View();
		}
		public IActionResult Kaydet(Yazar yazar) {

			k.Yazarkar.Add(yazar);
			k.SaveChanges();
			return RedirectToAction("YazarList");
		}
		public IActionResult YazarList()
		{
			var yazarlar = k.Yazarkar.ToList();
			return View();
		}
	}
}

WebApplication5/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebApplication5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication5</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication5.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication5</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Yazar" asp-action="Index">Yazar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Kitap" asp-action="Index">Kitap</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebApplication5 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebApplication5/Views/Yazar/Index.cshtml
@model WebApplication5.Models.Yazar

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<h4>Yazar</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Index">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="YazarAd" class="control-label"></label>
                <input asp-for="YazarAd" class="form-control" />
                <span asp-validation-for="YazarAd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="YazarSoyad" class="control-label"></label>
                <input asp-for="YazarSoyad" class="form-control" />
                <span asp-validation-for="YazarSoyad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}